import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
const JobDetailsModal = ({ job, isOpen, onClose, onApply }) => {
    if (!job)
        return null;
    return (_jsx(Dialog, { open: isOpen, onOpenChange: onClose, children: _jsxs(DialogContent, { className: "sm:max-w-[600px] max-h-[90vh] overflow-y-auto", children: [_jsx(DialogHeader, { children: _jsxs("div", { className: "flex items-center mb-4", children: [_jsx("img", { src: job.logo, alt: `${job.company} logo`, className: "w-16 h-16 rounded mr-4" }), _jsxs("div", { children: [_jsx(DialogTitle, { className: "text-xl font-semibold", children: job.title }), _jsx("p", { className: "text-gray-600", children: job.company })] })] }) }), _jsxs("div", { className: "grid grid-cols-2 gap-4 mb-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-500", children: "Location" }), _jsx("p", { className: "font-medium", children: job.location })] }), _jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-500", children: "Job Type" }), _jsx("p", { className: "font-medium", children: job.type })] }), _jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-500", children: "Experience" }), _jsxs("p", { className: "font-medium", children: [job.experience, " ", job.experience === 1 ? "year" : "years"] })] }), _jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-500", children: "Salary" }), _jsx("p", { className: "font-medium", children: job.salary })] })] }), _jsxs("div", { className: "mb-4", children: [_jsx("p", { className: "text-sm text-gray-500 mb-2", children: "Skills Required" }), _jsx("div", { className: "flex flex-wrap gap-1", children: job.skills.map((skill) => (_jsx(Badge, { variant: "secondary", className: "bg-blue-100 text-blue-800", children: skill.name }, skill.id))) })] }), _jsxs("div", { className: "mb-4", children: [_jsx("p", { className: "text-sm text-gray-500 mb-2", children: "Job Description" }), _jsx("div", { className: "whitespace-pre-line text-gray-800", children: job.description })] }), _jsxs(DialogFooter, { children: [_jsx(Button, { variant: "outline", onClick: onClose, className: "mr-2", children: "Close" }), _jsx(Button, { onClick: () => onApply(job), disabled: job.applied, children: job.applied ? "Applied" : "Apply Now" })] })] }) }));
};
export default JobDetailsModal;
